---
title: "Lab3_B"
author: "Sanyam Shilpakar"
date: "9/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

```{r}
surveys <- read_csv("data_raw/portal_data_joined.csv")
```

```{r}
str(surveys)
view(surveys)
```

# Common dplyr functions
```{r}
select(surveys, plot_id, species_id, weight)
select(surveys, -record_id, -species_id)
```

```{r}
filter(surveys, year == 1995)
```

```{r}
#surveys2 <- filter(surveys, weight < 5)
#surveys_sml <- select(surveys2, species_id, sex, weight)
surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
surveys_sml

```

```{r}
surverys_sml <- surveys %>%
  select(species_id, sex, weight) %>%
  filter(weight < 5)

surverys_sml
```
# CHALLENGE
```{r}
surveys_challenge1 <- surveys %>%
  select(year, sex, weight) %>%
  filter(year < 1995)

surveys_challenge1
```

# MUTATE
```{r}
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
```

```{r}
surveys %>%
   filter(!is.na(hindfoot_length)) %>%
  mutate(hindfoot_cm = hindfoot_length / 10) %>%
  select(species_id, hindfoot_cm) %>%
  head()
```

# SPLIT APPLY: summarize()
```{r}
surveys %>% 
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm= TRUE)) %>%
  head()

```

```{r}
surveys %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE)) %>%
  tail()
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) 

```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print(n = 15)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(desc(mean_weight))
```

```{r}
surveys %>%
  count(sex)
```

```{r}
surveys %>%
    group_by(sex) %>%
    summarise(count = n())
```

```{r}
surveys %>%
  count(sex, sort = TRUE)
```

```{r}
surveys %>%
  count(sex, species) %>%
  arrange(species, desc(n))
```

# CHALLENGE QUESTION 3
```{r}
surveys %>%
  count(plot_type)
```

```{r}
surveys %>%
  filter(!is.na(hindfoot_length)) %>%
  group_by(species_id) %>%
  summarize(mean_hindfoot_length = mean(hindfoot_length),
            min_hindfoot_length = min(hindfoot_length), 
            max_hindfoot_length = max(hindfoot_length),
            n = n()) 
```

```{r}
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(year) %>%
  filter(weight == max(weight)) %>%
  select(year, genus, species_id, weight) %>%
  arrange(year)
```

# RESHAPING WITH GATHER AND SPREAD
```{r}
surveys_gw <- surveys %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))

surveys_gw
str(surveys_gw)
```

```{r}
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)

str(surveys_spread)
```

```{r}
surveys_gw %>%
  spread(genus, mean_weight, fill = 0) %>%
  head()
```

# CHALLENGE QUESTIONS 4
```{r}
surveys_spread_genera <- surveys %>%
  group_by(plot_id, year) %>%
  summarize(n_genera = n_distinct(genus)) %>%
  spread(year, n_genera)

head(surveys_spread_genera)
```

```{r}
surveys_spread_genera %>%
  gather("year", "n_genera", -plot_id)
```

```{r}


surveys_long <- surveys %>%
  gather("measurement", "value", hindfoot_length, weight)
```

```{r}
surveys_long %>%
  group_by(year, measurement, plot_type) %>%
  summarize(mean_value = mean(value, na.rm=TRUE)) %>%
  spread(measurement, mean_value)
```

